repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/best-doctor/pre-commit-hooks
    rev: v1.0.11
    hooks:
    - id: mccabe-complexity
      name: Check functions complexity
      language: python
    - id: line-count
      name: Check number of lines in python files
      language: python

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
